title: Viet Le's Webisite
author:
  name: Quoc Viet Le (Viet Le)
  email: quocvietlework@gmail.com

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  My name is Viet Le. I am an undergraduate student in mathematics at University of Kansas. I will graduate in May 2024 and keep
  moving ahead to finish up next 4-5 year phD program in statistics or related field. 

  
  My interest primarily revolves around two pivotal topics: statistical learning and probability&statistical theory.

  
  1. In statistical learning, my work centers on understanding and developing ensemble learning techniques, particularly random forest and bagging. While investigating the statistics inference
  of bagging and its effect on generalized error of random forest, I have found some interesting properties of stochastic process on this algorithm. It also intrigues me to explore
  nonparametric Bayesian inference.

  
  2. In probability&statistical theory, my research focuses on understanding properties of Markov Chain Monte Carlo in general state space and MCMC algorithms. Since the MCMC algorithm is
  very important to calculate the posterior distribution in Bayesian statistics problem, I also do not exclude Bayesian statistics and its real-world applications from my study scope.
  
  

# Build settings

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Theme-specific settings

minima:
  # Minima date format.
  # Refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this.
  #
  # date_format: "%b %-d, %Y"

  # Generate social links in footer.
  #
  # social_links:
  #   - { platform: devto,          user_url: "https://dev.to/jekyll" }
  #   - { platform: dribbble,       user_url: "https://dribbble.com/jekyll" }
  #   - { platform: facebook,       user_url: "https://www.facebook.com/jekyll" }
  #   - { platform: flickr,         user_url: "https://www.flickr.com/photos/jekyll" }
  #   - { platform: github,         user_url: "https://github.com/jekyll/minima" }
  #   - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=qc6CJjYAAAAJ" }
  #   - { platform: instagram,      user_url: "https://www.instagram.com/jekyll" }
  #   - { platform: keybase,        user_url: "https://keybase.io/jekyll" }
  #   - { platform: linkedin,       user_url: "https://www.linkedin.com/in/jekyll" }
  #   - { platform: microdotblog,   user_url: "https://micro.blog/jekyll" }
  #   - { platform: pinterest,      user_url: "https://www.pinterest.com/jekyll" }
  #   - { platform: stackoverflow,  user_url: "https://stackoverflow.com/users/1234567/jekyll" }
  #   - { platform: telegram,       user_url: "https://t.me/jekyll" }
  #   - { platform: twitter,        user_url: "https://twitter.com/jekyllrb" }
  #   - { platform: x,              user_url: "https://x.com/jekyllrb" }
  #   - { platform: youtube,        user_url: "https://www.youtube.com/jekyll" }

# If you want to link only specific pages in your header, uncomment this and add the path to the pages in
# order as they should show up.
#
# header_pages:
#   - about.md

# Set to `true` to show excerpts on the homepage.
#
# show_excerpts: false
